Fix frontend features locale_spec
It failed with:

     ActionView::Template::Error:
       undefined method `content_tag' for Spree:Module

Probably due to recent changes in rails i18n api related to the security
patch in 4.0.2, see https://groups.google.com/forum/#!topic/ruby-security-ann/pLrh6DUw998
and https://github.com/rails/rails/commit/78790e4bceedc632cb40f9597792d7e27234138a