Fix for rspec-rails and rails 4.2.5.1
Fixes NoMethodError: Undefined Method `cache`

This can be removed as soon as doing so doesn't cause test errors.
See https://github.com/rspec/rspec-rails/issues/1532