Fix rubocop.yml for 0.53.0
The existing configuration was erroring with:

    Error: The `Style/TrailingCommaInLiteral` cop no longer exists.

This also locks the version to '~> 0.53.0' so that we don't
automatically get upgraded to a new incompatible in the future.