Check for presence of model_class before attempting to call it
Otherwise, this results in an undefined method error and has caused a segfault:

Exception `NilClass' at /path/to/spree/backend/app/controllers/spree/admin/base_controller.rb:19 -
undefined local variable or method `model_class' for
/path/to/spree/backend/app/controllers/spree/admin/base_controller.rb: [BUG] Segmentation fault
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0047 p:0026 s:0215 b:0215 l:000211 d:000214 BLOCK
c:0046 p:0012 s:0212 b:0212 l:000211 d:000211 METHOD /path/to/spree/backend/app/controllers/spree/admin/base_controller.rb:19
c:0045 p:0295 s:0208 b:0208 l:000207 d:000207 METHOD /path/to/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:462
c:0044 p:0115 s:0202 b:0202 l:000201 d:000201 METHOD /path/to/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405
c:0043 p:0027 s:0193 b:0193 l:000192 d:000192 METHOD /path/to/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385
c:0042 p:0024 s:0188 b:0188 l:000187 d:000187 METHOD /path/to/.rvm/gems/ruby-1.9.3-p392/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81
...