Fix assigning nil to default_wallet_payment_source=
Previously this was failing due to

    NoMethodError:
      undefined method `transaction' for nil:NilClass