Inherit from ActiveRecord::Migration version for all supported Rails
When attempting to run this migration on Rails 7.0 or Rails 7.1, an
error is produced if the version of the migration is `7.2`

```
ArgumentError: Unknown migration version "7.2"; expected one of "4.2", "5.0", "5.1", "5.2", "6.0", "6.1", "7.0", "7.1" (ArgumentError)
```

Since Rails versions 7.0, 7.1, and 7.2 are currently supported, this
migration should conform to, and inherit from, Rails 7.0 migrations.

(cherry picked from commit f5fc005196bea4c8aabb42bb8435591c9d7727aa)