Fix down migration
`bin/rails db:rollback`

fails with

```
Caused by:
ArgumentError: wrong number of arguments (given 2, expected 3)
```
This commit is fixing the rollback