Lock frontend and backend sprockets-rails 2.x
This is causing errors in our builds:

Asset was not declared to be precompiled in production.

and

NoMethodError: undefined method `register_engine' for nil:NilClass