`standardrb --fix`
The CI/CD linting task was upset about these files. They have nothing to
do with my current work, but I'm happy to append these changes to make
everything green, I guess.

     standard: Use Ruby Standard Style (https://github.com/standardrb/standard)
      api/spec/requests/spree/api/credit_cards_spec.rb:159:59: Style/RedundantInterpolation: Prefer `to_s` over string interpolation.
      api/spec/requests/spree/api/orders_spec.rb:81:69: Layout/SpaceInsideHashLiteralBraces: Space inside { detected.
      api/spec/requests/spree/api/orders_spec.rb:81:119: Layout/SpaceInsideHashLiteralBraces: Space inside } detected.
    standard: Run `standardrb --fix` to fix up to 3 problems.

    Error: Style/RedundantInterpolation: Prefer `to_s` over string interpolation.
    Error: Layout/SpaceInsideHashLiteralBraces: Space inside { detected.
    Error: Layout/SpaceInsideHashLiteralBraces: Space inside } detected.
    Error: Process completed with exit code 1.