Append to .gitignore only when file exists
This prevent the following error when the `.gitignore` file is
not present, for example when creating sandbox app:

  Rails::Generators::Error: The template [/path/to/solidus/admin/lib/solidus_admin/install_tailwindcss.rb] could not be loaded.
  Error: The file /path/to/solidus/sandbox/.gitignore does not appear to exist (Rails::Generators::Error)

  Caused by:
  Thor::Error: The file /path/to/solidus/sandbox/.gitignore does not appear to exist (Thor::Error)